@if($transaction->type == "Attestation")
@include("Printable.Attestation")
@elseif ($transaction->type == "Barangay Certification - Regular")
@include("Printable.BarangayCertificationRegular")
@elseif ($transaction->type == "Barangay Certification - First Time Job Seeker")
@include("Printable.BarangayCertificationFTJS")
@elseif ($transaction->type == "Barangay Clearance")
@include("Printable.BarangayClearance")
@elseif ($transaction->type == "Barangay Identification")
@include("Printable.BarangayIndentification")
@elseif ($transaction->type == "Barangay Indigency - Regular")
@include("Printable.CertificateOfIndigencyRegular")
@elseif ($transaction->type == "Barangay Indigency - Patient Name")
@include("Printable.CertificateOfIndigencyWPN")
@endif
